spring:
  application.name: medical
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  ai:
    openai:
      api-key: your-openai-api-key
      base-url: http://172.30.208.1:1234
      chat:
        options:
          temperature: 0.2

video:
  analysis:
    frames-per-second: 1

yolov8:
  service:
    url: http://localhost:8000
